name: Build CI

on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  submodule: recursive
                  depth: 1

            - name: Setup NodeJS v16
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Verify installation
              run: |
                  echo "NodeJS version: $(node -v)"
                  echo "NPM version: $(npm -v)"
 
            - name: Install dependencies
              run: |
                  npm ci

            - name: Build project
              run: |
                  npm run build
              env:
                  NODE_ENV: production

            - name: Deploy project
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: docs
                  publish_dir: '.' # Root directory
