name: Build CI

on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  submodule: recursive
                  depth: 1

            - name: Setup NodeJS v${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Verify installation
              run: |
                  echo "NodeJS version: $(node -v)"
                  echo "NPM version: $(npm -v)"
            - name: Install dependencies
              run: |
                  npm ci
            - name: Build project
              run: |
                  npm run build
                  
            - name: push
              uses: github-actions-x/commit@v2.8
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                push-branch: docs
                commit-message: '${{ matrix.node-version }} update dir structure'
                rebase: true
